insert into moviegenres
values (default, 'COMEDY');
insert into moviegenres
values (default, 'ADVENTURE');
insert into moviegenres
values (default, 'DRAMA');
insert into moviegenres
values (default, 'CRIME');
insert into moviegenres
values (default, 'BIOGRAPHY');
insert into moviegenres
values (default, 'ACTION');
insert into moviegenres
values (default, 'WAR');
insert into moviegenres
values (default, 'HORROR');
insert into moviegenres
values (default, 'THRILLER');
insert into moviegenres
values (default, 'DOCUMENTARY');
insert into moviegenres
values (default, 'FANTASY');

insert into countries
values (default, 'SPAIN');
insert into countries
values (default, 'USA');
insert into countries
values (default, 'FRANCE');
insert into countries
values (default, 'NEW_ZEALAND');
insert into countries
values (default, 'GREAT_BRITAIN');
insert into countries
values (default, 'CANADA');
insert into countries
values (default, 'GERMANY');
insert into countries
values (default, 'JAPAN');
insert into countries
values (default, 'ITALY');
insert into countries
values (default, 'AUSTRALIA');
insert into countries
values (default, 'INDIA');

insert into mpaaratings
values (default, 'G');
insert into mpaaratings
values (default, 'PG');
insert into mpaaratings
values (default, 'PG_13');
insert into mpaaratings
values (default, 'R');
insert into mpaaratings
values (default, 'NC_17');