INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (6, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (10, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (14, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (22, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (23, 'Peter Jackson', 1.65, 4, 163);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (24, 'Peter Jackson', 1.65, 4, 163);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (25, 'Peter Jackson', 1.65, 4, 163);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (91, 'Quentin Tarantino', 1.85, 5, 234);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (18, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (1, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (26, 'Testovich', 1.7, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (27, 'd', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (28, '2', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (29, '1', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (30, 'a', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (31, '1', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (32, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (33, 'Frank Darabont', 1.83, 3, 60);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (34, 'B', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (35, 'Asdf', 1.7, null, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (36, 'Asdf', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (40, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (41, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (42, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (43, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (44, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (45, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (46, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (47, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (48, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (49, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (50, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (51, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (52, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (54, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (55, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (56, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (57, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (58, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (59, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (60, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (61, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (62, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (63, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (64, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (65, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (66, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (67, 'Asdf', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (68, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (69, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (70, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (71, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (72, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (73, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (74, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (75, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (76, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (77, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (78, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (79, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (81, '1', 1, 5, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (92, 'Ridley Scott', 1.74, 7, 283);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (93, 'Andrew Adamson', 1.83, 4, 29);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (94, 'Guy Ritchie', 1.8, 7, 73);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (95, 'Testovich', 1.88, 12, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (37, 'Хлеб', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (87, 'LLL', 1.11, 2, 2);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (86, 'Testovich', 1.22, 12, 2);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (97, 'Test2', 1.8, 12, 2);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (80, 'Uefa', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (38, 'Asdf', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (39, 'Asdf', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (82, 'Аааа', 1.99, 12, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (53, 'Asdf', 1.87, 1, 100);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (96, 'Test', 1, 12, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (85, 'Тестович', 2.1, 12, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (83, 'Яна', 1.9, 12, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (84, 'Хрустим', 1.8, 5, 1);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (88, 'Robert Zemeckis', 1.83, 5, 131);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (89, 'Olivier Nakache', 1.69, 3, 33);
INSERT INTO persons (id, name, growthinmetres, nationality, filmcount) VALUES (90, 'Christopher Nolan', 1.81, 7, 74);
